AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CloudZero Notification Stack
    Send results of Connected Account Provisioning to a CloudZero Reactor.

  SAM Template for notification

Parameters:
  ReactorCallbackUrl:
    Type: String
    Default: 'null'
    Description: |
      CloudZero Reactor Queue Url; receives callbacks from this template
  Version:
    Type: String
    Default: 'latest'
    Description: |
      Version to target when deploying the stack. `latest` should be used by default.

Conditions:
  ValidReactorCallbackUrl: !Not
  - !Equals [!Ref ReactorCallbackUrl, 'null']

Globals:
  Function:
    Runtime: python3.12
    MemorySize: 512
    Timeout: 30

Resources:
  NotificationFunction:
    Type: AWS::Serverless::Function
    Condition: ValidReactorCallbackUrl
    Properties:
      CodeUri:
        Bucket: !Sub 'cz-provision-account-${AWS::Region}'
        Key: !Sub ${Version}/services/notification.zip
      Handler: src.app.handler
      Policies:
      - AWSCloudFormationReadOnlyAccess
      Environment:
        Variables:
          VERSION: '1'

Outputs:
  Arn:
    Condition: ValidReactorCallbackUrl
    Value: !GetAtt NotificationFunction.Arn
    Description: Notification Function ARN
