# Copyright (c) 2016-present, CloudZero, Inc. All rights reserved.
# Licensed under the BSD-style license. See LICENSE file in the project root for full license information.

# This action will do a merge from one branch to another

name: Merge From To
description: Merge from one branch to another

inputs:
  from-sha:
    description: "Commit sha to merge from"
    required: true
  from-branch:
    description: "Branch to merge from"
    required: true
    default: "develop"
  to:
    description: "Branch to merge to"
    required: true
    default: "main"
  app_id:
    description: "GitHub App ID"
    required: true
  private_key:
    description: "GitHub App Private Key"
    required: true

runs:
  using: composite
  steps:
    - name: Generate a token for the GitHub App so that push triggers a workflow
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ inputs.app_id }}
        private_key: ${{ inputs.private_key }}

    - uses: actions/checkout@v3
      # replace token with the token generated by the previous action, so all git commands use it
      with:
        ref: ${{ inputs.from-branch }}
        token: ${{ steps.generate_token.outputs.token }}

    - name: git config, merge, and push
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      shell: bash
      run: |
        git config --local user.email "ops@cloudzero.com"
        git config --local user.name "Automated CZ Release"
        git fetch --unshallow
        git checkout ${{ inputs.to}}
        git pull
        git merge --no-edit --ff-only ${{ inputs.from-sha }}
        git push origin ${{ inputs.to }}
