# -*- coding: utf-8 -*-
# Copyright (c) 2016-present, CloudZero, Inc. All rights reserved.
# Licensed under the BSD-style license. See LICENSE file in the project root for full license information.

AWSTemplateFormatVersion: '2010-09-09'
Description: CloudZero Connected Account Template

Parameters:
  Namespace:
    Type: String

Resources:
  # TODO: Fill In

Outputs:
  # TODO: Fill In
