# -*- coding: utf-8 -*-
# Copyright (c) 2016-present, CloudZero, Inc. All rights reserved.
# Licensed under the BSD-style license. See LICENSE file in the project root for full license information.

AWSTemplateFormatVersion: '2010-09-09'
Description: CloudZero Provision Account CFN Templates

Parameters:
  FeatureName:
    Type: String
  Namespace:
    Type: String

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub cz-${FeatureName}
  Policy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource:
              - !Sub ${Bucket.Arn}
              - !Sub '${Bucket.Arn}/*'
            Principal: '*'

Outputs:
  BucketName:
    Value: !Ref Bucket
    Description: CloudZero Provision Account CFN Templates Bucket Name
    Export:
      Name: !Sub cz-${FeatureName}:BucketName
  BucketArn:
    Value: !GetAtt Bucket.Arn
    Description: CloudZero Provision Account CFN Templates Bucket Arn
    Export:
      Name: !Sub cz-${FeatureName}:BucketArn
