AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CZ Discovery Stack:
    Determine the Types CZ can apply to the current account.

  SAM Template for discovery

Globals:
  Function:
    Runtime: python3.7
    MemorySize: 256
    Timeout: 10

Resources:
  DiscoveryFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri:
        Bucket: !Sub 'cz-provision-account-${AWS::Region}'
        Key: latest/services/discovery.zip
      Handler: src.app.handler
      Policies:
        - AmazonS3ReadOnlyAccess
        - AWSCloudTrailReadOnlyAccess
        - Billing
      Environment:
        Variables:
          VERSION: '2'

  DiscoveryResource:
    Type: Custom::Discovery
    Properties:
      ServiceToken: !GetAtt DiscoveryFunction.Arn
      AccountId: !Sub ${AWS::AccountId}
      Version: '2'

Outputs:
  AuditCloudTrailBucketName:
    Value: !GetAtt DiscoveryResource.AuditCloudTrailBucketName
  AuditCloudTrailBucketPrefix:
    Value: !GetAtt DiscoveryResource.AuditCloudTrailBucketPrefix
  CloudTrailSNSTopicArn:
    Value: !GetAtt DiscoveryResource.CloudTrailSNSTopicArn
  CloudTrailTrailArn:
    Value: !GetAtt DiscoveryResource.CloudTrailTrailArn
  IsAuditAccount:
    Value: !GetAtt DiscoveryResource.IsAuditAccount
  IsMasterPayerAccount:
    Value: !GetAtt DiscoveryResource.IsMasterPayerAccount
  IsCloudTrailOwnerAccount:
    Value: !GetAtt DiscoveryResource.IsCloudTrailOwnerAccount
  IsResourceOwnerAccount:
    Value: !GetAtt DiscoveryResource.IsResourceOwnerAccount
  MasterPayerBillingBucketName:
    Value: !GetAtt DiscoveryResource.MasterPayerBillingBucketName
  MasterPayerBillingBucketPrefix:
    Value: !GetAtt DiscoveryResource.MasterPayerBillingBucketPrefix
  RemoteCloudTrailBucket:
    Value: !GetAtt DiscoveryResource.RemoteCloudTrailBucket

