AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CZ Discovery Stack:
    Determine the Types CZ can apply to the current account.

  SAM Template for discovery

Parameters:
  Version:
    Type: String
    Default: 'latest'
    Description: |
      Version to target when deploying the stack. `latest` should be used by default.

Globals:
  Function:
    Runtime: python3.12
    MemorySize: 512
    Timeout: 30

Resources:
  DiscoveryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: !Sub 'cz-provision-account-${AWS::Region}'
        Key: !Sub ${Version}/services/discovery.zip
      Handler: src.app.handler
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Sid: CZDiscovery20190912
          Effect: Allow
          Action:
          - s3:ListAllMyBuckets
          - cur:DescribeReportDefinitions
          - bcm-data-exports:ListExports
          - bcm-data-exports:GetExport
          - organizations:DescribeOrganization
          - cloudformation:DescribeStacks
          Resource: '*'
      Environment:
        Variables:
          VERSION: '20230523'

  DiscoveryResource:
    Type: Custom::Discovery
    Properties:
      ServiceToken: !GetAtt DiscoveryFunction.Arn
      AccountId: !Sub ${AWS::AccountId}
      Version: !Sub ${Version}

Outputs:
  IsResourceConnection:
    Value: !GetAtt DiscoveryResource.IsResourceConnection
  IsBillingConnection:
    Value: !GetAtt DiscoveryResource.IsBillingConnection
  IsOrganizationMasterAccount:
    Value: !GetAtt DiscoveryResource.IsOrganizationMasterAccount
  IsAccountOutsideOrganization:
    Value: !GetAtt DiscoveryResource.IsAccountOutsideOrganization
  BillingBucketName:
    Value: !GetAtt DiscoveryResource.BillingBucketName
  BillingBucketPath:
    Value: !GetAtt DiscoveryResource.BillingBucketPath
  BillingBucketArns:
    Value: !GetAtt DiscoveryResource.BillingBucketArns
  BillingReportFormat:
    Value: !GetAtt DiscoveryResource.BillingReportFormat
  DetectedLegacyConnectionStacks:
    Value: !GetAtt DiscoveryResource.DetectedLegacyConnectionStacks
