AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CZ Discovery Stack:
    Determine the Types CZ can apply to the current account.

  SAM Template for discovery

Parameters:
  Version:
    Type: String
    Default: 'latest'
    Description: |
      Version to target when deploying the stack. `latest` should be used by default.

Globals:
  Function:
    Runtime: python3.12
    MemorySize: 512
    Timeout: 30

Resources:
  DiscoveryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: !Sub 'cz-provision-account-${AWS::Region}'
        Key: !Sub ${Version}/services/discovery.zip
      Handler: src.app.handler
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Sid: CZDiscovery20190912
          Effect: Allow
          Action:
          - cloudtrail:DescribeTrails
          - s3:ListAllMyBuckets
          - cur:DescribeReportDefinitions
          - organizations:DescribeOrganization
          Resource: '*'
      Environment:
        Variables:
          VERSION: '20230523'

  DiscoveryResource:
    Type: Custom::Discovery
    Properties:
      ServiceToken: !GetAtt DiscoveryFunction.Arn
      AccountId: !Sub ${AWS::AccountId}
      Version: '20230523'

Outputs:
  AuditCloudTrailBucketName:
    Value: !GetAtt DiscoveryResource.AuditCloudTrailBucketName
  AuditCloudTrailBucketPrefix:
    Value: !GetAtt DiscoveryResource.AuditCloudTrailBucketPrefix
  CloudTrailSNSTopicArn:
    Value: !GetAtt DiscoveryResource.CloudTrailSNSTopicArn
  CloudTrailTrailArn:
    Value: !GetAtt DiscoveryResource.CloudTrailTrailArn
  IsAuditAccount:
    Value: !GetAtt DiscoveryResource.IsAuditAccount
  IsMasterPayerAccount:
    Value: !GetAtt DiscoveryResource.IsMasterPayerAccount
  IsCloudTrailOwnerAccount:
    Value: !GetAtt DiscoveryResource.IsCloudTrailOwnerAccount
  IsResourceOwnerAccount:
    Value: !GetAtt DiscoveryResource.IsResourceOwnerAccount
  MasterPayerBillingBucketName:
    Value: !GetAtt DiscoveryResource.MasterPayerBillingBucketName
  MasterPayerBillingBucketPath:
    Value: !GetAtt DiscoveryResource.MasterPayerBillingBucketPath
  RemoteCloudTrailBucket:
    Value: !GetAtt DiscoveryResource.RemoteCloudTrailBucket
  VisibleCloudTrailArns:
    Value: !GetAtt DiscoveryResource.VisibleCloudTrailArns
  IsOrganizationTrail:
    Value: !GetAtt DiscoveryResource.IsOrganizationTrail
  IsOrganizationMasterAccount:
    Value: !GetAtt DiscoveryResource.IsOrganizationMasterAccount
  IsAccountOutsideOrganization:
    Value: !GetAtt DiscoveryResource.IsAccountOutsideOrganization
