# -*- coding: utf-8 -*-
# Copyright (c) 2016-present, CloudZero, Inc. All rights reserved.
# Licensed under the BSD-style license. See LICENSE file in the project root for full license information.

AWSTemplateFormatVersion: '2010-09-09'
Description: CloudZero Connected Account Template

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Account Name Metadata for your Account
        Parameters:
          - AccountName
      - Label:
          default: CloudZero Cross Account Access
        Parameters:
          - ExternalId
          - ReactorAccountId
      - Label:
          default: CloudZero Callback Information
        Parameters:
          - ReactorId
          - ReactorCallbackUrl
    ParameterLabels:
      AccountName:
        default: |
          Optional Name you can set for your AWS Account; you can use this as a descriptive alias for AccountId
      ExternalId:
        default: |
          Unique ExternalId for your Organization; Generated by CloudZero; Used for Cross Account Roles
      ReactorAccountId:
        default: |
          CloudZero AWS AccountID; Used for Cross Account Roles
      ReactorId:
        default: |
          CloudZero Reactor ID; Used to Uniquely ID the CloudZero System Ingesting your Data
      ReactorCallbackUrl:
        default: |
          CloudZero Reactor SQS Queue receives callbacks from this template

Parameters:
  AccountName:
    Type: String
    Default: ''
    Description: |
      Optional Name you can set for your AWS Account; you can use this as a
      descriptive alias for AccountId. It's useful to set this here when you
      are automating provisioning many accounts with this template.
  ExternalId:
    Type: String
    Description: |
      Unique ExternalId for Customer Organization; for cross-account Role Access and
      associating this template with a Customer Organization
  ReactorAccountId:
    Type: String
    Default: '061190967865'
    Description: |
      CloudZero AWS AccountID; for cross-account Role Access
  ReactorId:
    Type: String
    Default: 'f7a07d02-d509-4e8d-9fb9-69c7985a6bd8'
    Description: |
      CloudZero Reactor ID; Used to Uniquely ID the CloudZero System Ingesting your Data
  ReactorCallbackUrl:
    Type: String
    Default: 'null'
    Description: |
      CloudZero Reactor Queue Url; receives callbacks from this template

Conditions:
  ValidReactorCallbackUrl: !Not
    - !Equals [ !Ref ReactorCallbackUrl, 'null' ]

Resources:
  Discovery:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
        - Key: cloudzero-stack
          Value: !Ref AWS::StackName
        - Key: cloudzero-reactor-account-id
          Value: !Ref ReactorAccountId
      TemplateURL: https://s3.amazonaws.com/cz-provision-account/latest/services/discovery.yaml

  # TODO: This Legacy Account supports older reactors that require all permissions in a single role
  LegacyAccount:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
        - Key: cloudzero-stack
          Value: !Ref AWS::StackName
        - Key: cloudzero-reactor-account-id
          Value: !Ref ReactorAccountId
      Parameters:
        IsResourceOwnerAccount: !GetAtt Discovery.Outputs.IsResourceOwnerAccount
        IsAuditAccount: !GetAtt Discovery.Outputs.IsAuditAccount
        IsMasterPayerAccount: !GetAtt Discovery.Outputs.IsMasterPayerAccount
        IsCloudTrailOwnerAccount: !GetAtt Discovery.Outputs.IsCloudTrailOwnerAccount
        ExternalId: !Ref ExternalId
        ReactorAccountId: !Ref ReactorAccountId
        AuditCloudTrailBucketName: !GetAtt Discovery.Outputs.AuditCloudTrailBucketName
        MasterPayerBillingBucketName: !GetAtt Discovery.Outputs.MasterPayerBillingBucketName
        CloudTrailSQSQueueArn: !GetAtt CloudTrailOwnerAccount.Outputs.SQSQueueArn
      TemplateURL: https://s3.amazonaws.com/cz-provision-account/latest/services/account_type/legacy.yaml


  ResourceOwnerAccount:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
        - Key: cloudzero-stack
          Value: !Ref AWS::StackName
        - Key: cloudzero-reactor-account-id
          Value: !Ref ReactorAccountId
      Parameters:
        IsResourceOwnerAccount: !GetAtt Discovery.Outputs.IsResourceOwnerAccount
        ExternalId: !Ref ExternalId
        ReactorAccountId: !Ref ReactorAccountId
      TemplateURL: https://s3.amazonaws.com/cz-provision-account/latest/services/account_type/resource_owner.yaml

  CloudTrailOwnerAccount:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
        - Key: cloudzero-stack
          Value: !Ref AWS::StackName
        - Key: cloudzero-reactor-account-id
          Value: !Ref ReactorAccountId
      Parameters:
        IsCloudTrailOwnerAccount: !GetAtt Discovery.Outputs.IsCloudTrailOwnerAccount
        CloudTrailSNSTopicArn: !GetAtt Discovery.Outputs.CloudTrailSNSTopicArn
        ReactorAccountId: !Ref ReactorAccountId
      TemplateURL: https://s3.amazonaws.com/cz-provision-account/latest/services/account_type/cloudtrail_owner.yaml

  AuditAccount:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
        - Key: cloudzero-stack
          Value: !Ref AWS::StackName
        - Key: cloudzero-reactor-account-id
          Value: !Ref ReactorAccountId
      Parameters:
        IsAuditAccount: !GetAtt Discovery.Outputs.IsAuditAccount
        AuditCloudTrailBucketName: !GetAtt Discovery.Outputs.AuditCloudTrailBucketName
        ExternalId: !Ref ExternalId
        ReactorAccountId: !Ref ReactorAccountId
      TemplateURL: https://s3.amazonaws.com/cz-provision-account/latest/services/account_type/audit.yaml

  MasterPayerAccount:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
        - Key: cloudzero-stack
          Value: !Ref AWS::StackName
        - Key: cloudzero-reactor-account-id
          Value: !Ref ReactorAccountId
      Parameters:
        IsMasterPayerAccount: !GetAtt Discovery.Outputs.IsMasterPayerAccount
        MasterPayerBillingBucketName: !GetAtt Discovery.Outputs.MasterPayerBillingBucketName
        ExternalId: !Ref ExternalId
        ReactorAccountId: !Ref ReactorAccountId
      TemplateURL: https://s3.amazonaws.com/cz-provision-account/latest/services/account_type/master_payer.yaml


  NotificationFunctionStack:
    Type: AWS::CloudFormation::Stack
    Condition: ValidReactorCallbackUrl
    Properties:
      Tags:
        - Key: cloudzero-stack
          Value: !Ref AWS::StackName
        - Key: cloudzero-reactor-account-id
          Value: !Ref ReactorAccountId
      Parameters:
        ReactorCallbackUrl: !Ref ReactorCallbackUrl
      TemplateURL: https://s3.amazonaws.com/cz-provision-account/latest/services/notification.yaml


  NotifyCloudZeroReactor:
    Type: Custom::NotifyCloudZero
    Condition: ValidReactorCallbackUrl    
    Properties:
      Tags:
        - Key: cloudzero-stack
          Value: !Ref AWS::StackName
        - Key: cloudzero-reactor-account-id
          Value: !Ref ReactorAccountId
      ServiceToken: !GetAtt NotificationFunctionStack.Outputs.Arn
      AccountId: !Sub ${AWS::AccountId}
      Version: '1'
      # Parameters from Other Resources in this Stack
      ExternalId: !Ref ExternalId
      ReactorCallbackUrl: !Ref ReactorCallbackUrl
      AccountName: !Ref AccountName
      ReactorId: !Ref ReactorId
      # References to other stacks; it's easier for _this_ Resource to simply grab the outputs
      # programmatically b/c some of the outputs are conditional.
      Stacks:
        Discovery: !Ref Discovery
        ResourceOwnerAccount: !Ref ResourceOwnerAccount
        CloudTrailOwnerAccount: !Ref CloudTrailOwnerAccount
        AuditAccount: !Ref AuditAccount
        MasterPayerAccount: !Ref MasterPayerAccount



Outputs:
  BillingBucket:
    Value: !GetAtt Discovery.Outputs.MasterPayerBillingBucketName
  # BillingPrefix:
  #   Value: !GetAtt DiscoveryResource.MasterPayerBillingBucketPrefix
  CloudTrailArn:
    Value: !GetAtt Discovery.Outputs.CloudTrailTrailArn
  CloudTrailBucketPrefix:
    Value: !GetAtt Discovery.Outputs.AuditCloudTrailBucketPrefix
  CloudTrailBucket:
    Value: !GetAtt Discovery.Outputs.AuditCloudTrailBucketName
  ConnectedAccountId:
    Value: !Ref 'AWS::AccountId'
  ConnectedAccountName:
    Value: !Ref AccountName
  ExternalId:
    Value: !Ref ExternalId
  Region:
    Value: !Ref 'AWS::Region'
  RemoteCloudTrailBucket:
    Value: !GetAtt Discovery.Outputs.RemoteCloudTrailBucket
  RemoteCloudTrailId:
    Value: !Sub 'AccountId of the account that owns the ${Discovery.Outputs.AuditCloudTrailBucketName} bucket.'
  RemoteCloudTrailRole:
    Value: !Sub 'ClouZero RoleArn in the account that owns the ${Discovery.Outputs.AuditCloudTrailBucketName} bucket.'
  RoleArn:
    Value: !GetAtt LegacyAccount.Outputs.RoleArn
  SnsArn:
    Value: !GetAtt Discovery.Outputs.CloudTrailSNSTopicArn
  SqsArn:
    Value: !GetAtt CloudTrailOwnerAccount.Outputs.SQSQueueArn

