# -*- coding: utf-8 -*-
# Copyright (c) 2016-present, CloudZero, Inc. All rights reserved.
# Licensed under the BSD-style license. See LICENSE file in the project root for full license information.

AWSTemplateFormatVersion: '2010-09-09'
Description: CloudZero Connected Account Template

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Account Name Metadata for your Account
        Parameters:
          - AccountName
      - Label:
          default: CloudZero Cross Account Access
        Parameters:
          - ExternalId
          - ReactorAccountId
      - Label:
          default: CloudZero Callback Information
        Parameters:
          - ReactorId
          - ReactorSQSQueueUrl
    ParameterLabels:
      AccountName:
        default: |
          Optional Name you can set for your AWS Account; you can use this as a descriptive alias for AccountId
      ExternalId:
        default: |
          Unique ExternalId for your Organization; Generated by CloudZero; Used for Cross Account Roles
      ReactorAccountId:
        default: |
          CloudZero AWS AccountID; Used for Cross Account Roles
      ReactorId:
        default: |
          CloudZero Reactor ID; Used to Uniquely ID the CloudZero System Ingesting your Data
      ReactorSQSQueueUrl:
        default: |
          CloudZero Reactor SQS Queue receives callbacks from this template

Parameters:
  AccountName:
    Type: String
    Default: ''
    Description: |
      Optional Name you can set for your AWS Account; you can use this as a
      descriptive alias for AccountId. It's useful to set this here when you
      are automating provisioning many  accounts with this template.
  ExternalId:
    Type: String
    Description: |
      Unique ExternalId for Customer Organization; for cross-account Role Access and
      associating this template with a Customer Organization
  ReactorAccountId:
    Type: String
    Default: '061190967865'
    Description: |
      CloudZero AWS AccountID; for cross-account Role Access
  ReactorId:
    Type: String
    Default: 'f7a07d02-d509-4e8d-9fb9-69c7985a6bd8'
    Description: |
      CloudZero Reactor ID; Used to Uniquely ID the CloudZero System Ingesting your Data
  ReactorSQSQueueUrl:
    Type: String
    Default: Does not Exist Yet
    Description: |
      CloudZero Reactor Queue Url; receives callbacks from this template

Resources:
  Discovery:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
        - Key: cloudzero-stack
          Value: !Ref AWS::StackName
        - Key: cloudzero-reactor-account-id
          Value: !Ref ReactorAccountId
      TemplateURL: https://s3.amazonaws.com/cz-provision-account/latest/services/discovery.yaml

  ResourceOwnerAccount:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
        - Key: cloudzero-stack
          Value: !Ref AWS::StackName
        - Key: cloudzero-reactor-account-id
          Value: !Ref ReactorAccountId
      Parameters:
        IsResourceOwnerAccount: !GetAtt Discovery.Outputs.IsResourceOwnerAccount
        ExternalId: !Ref ExternalId
        ReactorAccountId: !Ref ReactorAccountId
      TemplateURL: https://s3.amazonaws.com/cz-provision-account/latest/services/account_type/resource_owner.yaml

  CloudTrailOwnerAccount:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
        - Key: cloudzero-stack
          Value: !Ref AWS::StackName
        - Key: cloudzero-reactor-account-id
          Value: !Ref ReactorAccountId
      Parameters:
        IsCloudTrailOwnerAccount: !GetAtt Discovery.Outputs.IsCloudTrailOwnerAccount
        CloudTrailSNSTopicArn: !GetAtt Discovery.Outputs.CloudTrailSNSTopicArn
        ReactorAccountId: !Ref ReactorAccountId
      TemplateURL: https://s3.amazonaws.com/cz-provision-account/latest/services/account_type/cloudtrail_owner.yaml

  AuditAccount:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
        - Key: cloudzero-stack
          Value: !Ref AWS::StackName
        - Key: cloudzero-reactor-account-id
          Value: !Ref ReactorAccountId
      Parameters:
        IsAuditAccount: !GetAtt Discovery.Outputs.IsAuditAccount
        AuditCloudTrailBucketName: !GetAtt Discovery.Outputs.AuditCloudTrailBucketName
        ExternalId: !Ref ExternalId
        ReactorAccountId: !Ref ReactorAccountId
      TemplateURL: https://s3.amazonaws.com/cz-provision-account/latest/services/account_type/audit.yaml

  MasterPayerAccount:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
        - Key: cloudzero-stack
          Value: !Ref AWS::StackName
        - Key: cloudzero-reactor-account-id
          Value: !Ref ReactorAccountId
      Parameters:
        IsMasterPayerAccount: !GetAtt Discovery.Outputs.IsMasterPayerAccount
        MasterPayerBillingBucketName: !GetAtt Discovery.Outputs.MasterPayerBillingBucketName
        ExternalId: !Ref ExternalId
        ReactorAccountId: !Ref ReactorAccountId
      TemplateURL: https://s3.amazonaws.com/cz-provision-account/latest/services/account_type/master_payer.yaml


  # NotifyCloudZeroReactor:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     Tags:
  #       - Key: cloudzero-stack
  #         Value: !Ref AWS::StackName
  #       - Key: cloudzero-reactor-account-id
  #         Value: !Ref ReactorAccountId
  #     Parameters:
  #       # Parameters
  #       ExternalId: !Ref ExternalId
  #       ReactorSQSQueueUrl: !Ref ReactorSQSQueueUrl
  #       AccountName: !Ref AccountName
  #       ReactorId: !Ref ReactorId
  #       # Discovery Output
  #       AuditCloudTrailBucketName: !GetAtt Discovery.Outputs.AuditCloudTrailBucketName
  #       CloudTrailSNSTopicArn: !GetAtt Discovery.Outputs.CloudTrailSNSTopicArn
  #       IsAuditAccount: !GetAtt Discovery.Outputs.IsAuditAccount
  #       IsMasterPayerAccount: !GetAtt Discovery.Outputs.IsMasterPayerAccount
  #       IsCloudTrailOwnerAccount: !GetAtt Discovery.Outputs.IsCloudTrailOwnerAccount
  #       IsResourceOwnerAccount: !GetAtt Discovery.Outputs.IsResourceOwnerAccount
  #       MasterPayerBillingBucketName: !GetAtt Discovery.Outputs.MasterPayerBillingBucketName
  #       # Account Types Output
  #       ResourceOwnerRoleArn: !GetAtt ResourceOwnerAccount.Outputs.RoleArn
  #       CloudTrailOwnerSQSQueueArn: !GetAtt CloudTrailOwnerAccount.Outputs.SQSQueueArn
  #       CloudTrailOwnerSQSQueuePolicyArn: !GetAtt CloudTrailOwnerAccount.Outputs.SQSQueuePolicyArn
  #       CloudTrailOwnerSNSTopicPolicyArn: !GetAtt CloudTrailOwnerAccount.Outputs.SNSTopicPolicyArn
  #       AuditRoleArn: !GetAtt AuditAccount.Outputs.RoleArn
  #       MasterPayerAccountRoleArn: !GetAtt MasterPayerAccount.Outputs.RoleArn
  #     TemplateURL: https://s3.amazonaws.com/cz-provision-account/latest/services/notify.yaml

Outputs:
  # Parameters
  AccountName:
    Value: !Ref AccountName
    Description: The Account Name metadata to associated with this AccountId
  ExternalId:
    Value: !Ref ExternalId
    Description: The External ID used for cross account roles
  ReactorId:
    Value: !Ref ReactorId
    Description: The Reactor Id associated with this link
  ReactorAccountId:
    Value: !Ref ReactorAccountId
    Description: The Reactor Account Id used for cross account roles
  ReactorSQSQueueUrl:
    Value: !Ref ReactorSQSQueueUrl
    Description: The Reactor SQS Queue this template sends notifications to
  # Discovery
  IsAuditAccount:
    Value: !GetAtt Discovery.Outputs.IsAuditAccount
    Description: Does this Account have a CloudTrail Audit Bucket?
  IsCloudTrailOwnerAccount:
    Value: !GetAtt Discovery.Outputs.IsCloudTrailOwnerAccount
    Description: Does this Account have a CloudTrail Trail?
  IsMasterPayerAccount:
    Value: !GetAtt Discovery.Outputs.IsMasterPayerAccount
    Description: Does this Account have a Billing Report Bucket?
  IsResourceOwnerAccount:
    Value: !GetAtt Discovery.Outputs.IsResourceOwnerAccount
    Description: Does this Account own AWS Resources?
