# -*- coding: utf-8 -*-
# Copyright (c) 2016-present, CloudZero, Inc. All rights reserved.
# Licensed under the BSD-style license. See LICENSE file in the project root for full license information.

AWSTemplateFormatVersion: "2010-09-09"
Description: CloudZero Resource Owner StackSet Deployment Wrapper

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: StackSet Configuration
        Parameters:
          - StackSetName
          - OrganizationRootId
      - Label:
          default: Required Parameters for Resource Owner Stack
        Parameters:
          - ExternalId
      - Label:
          default: Optional Parameters
        Parameters:
          - Version
          - ResourceRoleName
    ParameterLabels:
      StackSetName:
        default: Name for the StackSet
      OrganizationRootId:
        default: Organization Root ID (required for auto-deployment)
      ExternalId:
        default: Unique ExternalId for your Organization
      Version:
        default: Version to deploy
      ResourceRoleName:
        default: Name for the resource owner role

Parameters:
  StackSetName:
    Type: String
    Default: CloudZero-ResourceOwner-StackSet
    Description: Name for the StackSet

  OrganizationRootId:
    Type: String
    AllowedPattern: ".+"
    Description: |
      Your AWS Organization root ID (e.g., r-abcd).
      Required for automatic deployment via CloudFormation.
      Find this in AWS Organizations console → Organize accounts tab.
    ConstraintDescription: "Must provide the AWS Organization root ID (e.g., r-abcd)."

  Regions:
    Type: CommaDelimitedList
    AllowedPattern: ".+"
    Default: "us-east-1"
    Description: "List of AWS regions to deploy to"
    ConstraintDescription: "Must be valid AWS region names separated by commas"

  ResourceRoleName:
    Type: String
    Default: "cloudzero-resource-owner-role"
    Description: |
      Name for the resource owner role. Defaults to 'cloudzero-resource-owner-role'.

  ExternalId:
    Type: String
    AllowedPattern: ".+"
    Description: Unique ExternalId for your Organization
    ConstraintDescription: "Must provide the ExternalId"

  Version:
    Type: String
    Default: "latest"
    Description: Version to deploy

Resources:
  ResourceOwnerStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: !Ref StackSetName
      Description: CloudZero Resource Owner Account StackSet
      TemplateURL: !Sub https://cz-provision-account.s3.amazonaws.com/${Version}/services/resource_member_stackset_dev.yaml
      Parameters:
        - ParameterKey: ExternalId
          ParameterValue: !Ref ExternalId
        - ParameterKey: ResourceRoleName
          ParameterValue: !Ref ResourceRoleName
      Capabilities:
        - CAPABILITY_IAM
        - CAPABILITY_NAMED_IAM
      PermissionModel: SERVICE_MANAGED
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds:
              - !Ref OrganizationRootId
          Regions: !Ref Regions
          ParameterOverrides:
            - ParameterKey: ExternalId
              ParameterValue: !Ref ExternalId
            - ParameterKey: Version
              ParameterValue: !Ref Version
            - ParameterKey: ResourceRoleName
              ParameterValue: !Ref ResourceRoleName

Outputs:
  StackSetId:
    Description: ID of the created StackSet
    Value: !Ref ResourceOwnerStackSet
  StackSetName:
    Description: Name of the created StackSet
    Value: !Ref StackSetName
