image:
  repository: cloudzero/cloudwatch-agent
  tag: cz-cloudwatchagent-0853e59.1
  pullPolicy: IfNotPresent

clusterName: cluster_name

resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 50m
    memory: 50Mi

serviceAccount:
  create: true
  name:

hostNetwork: true
