image:
  repository: cloudzero/cloudwatch-agent
  tag: 0.0.0
  pullPolicy: IfNotPresent

clusterName: cluster_name

resources:
  limits:
    cpu: 400m
    memory: 2000Mi
  requests:
    cpu: 100m
    memory: 100Mi

serviceAccount:
  create: true
  name:

hostNetwork: true
