image:
  repository: cloudzero/cloudwatch-agent
  tag: 1.247350.beta1
  pullPolicy: IfNotPresent

clusterName: cluster_name

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi

serviceAccount:
  create: true
  name:

hostNetwork: false
