AWSTemplateFormatVersion: '2010-09-09'


Description: CloudZero CloudTrail Owner Template


Parameters:
  IsCloudTrailOwnerAccount:
    Description: Flag that indicates if this account owns the cloudtrail
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
  CloudTrailSNSTopicArn:
    Description: 'The CloudZero SNS Topic ARN responsible for receiving notifications from the cloudtrail'
    Type: String
  ReactorAccountId:
    Description: The CloudZero reactor AWS account ID
    Type: String
    Default: '061190967865'


Conditions:
  CreateResources: !And [ !Not [ !Equals [ !Ref CloudTrailSNSTopicArn, 'null' ] ], !Equals [ !Ref IsCloudTrailOwnerAccount, 'true' ] ]


Resources:

  SqsQueue:
    Type: 'AWS::SQS::Queue'
    Condition: CreateResources
    Properties:
      Tags:
        - Key: cloudzero-stack
          Value: !Ref AWS::StackName
        - Key: cloudzero-reactor-account-id
          Value: !Ref ReactorAccountId

  SnsSubscription:
    Type: AWS::SNS::Subscription
    Condition: CreateResources
    Properties:
      Protocol: sqs
      Endpoint: !GetAtt SqsQueue.Arn
      Region: !Ref "AWS::Region"
      TopicArn: !Ref CloudTrailSNSTopicArn

  SqsPolicy:
    Type: 'AWS::SQS::QueuePolicy'
    Condition: CreateResources
    Properties:
      Queues:
        - !Ref SqsQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'sqs:SendMessage'
            Principal:
              AWS: "*"
            Resource: "*"
            Condition:
              ArnEquals:
                'aws:SourceArn': !Ref CloudTrailSNSTopicArn


Outputs:
  SQSQueueArn:
    Description: The CloudZero SQS queue
    Value: !If [ CreateResources, !GetAtt SqsQueue.Arn, 'null' ]
  SQSQueuePolicyArn:
    Condition: CreateResources
    Description: The CloudZero SQS queue policy
    Value: !Ref SqsPolicy
