# -*- coding: utf-8 -*-
# Copyright (c) 2016-present, CloudZero, Inc. All rights reserved.
# Licensed under the BSD-style license. See LICENSE file in the project root for full license information.

AWSTemplateFormatVersion: '2010-09-09'
Description: CloudZero Resource Owner Account Template

Parameters:
  ExternalId:
    Type: String
    Description: |
      Unique ExternalId for Customer Organization; for cross-account Role Access and
      associating this template with a Customer Organization
  ReactorAccountId:
    Type: String
    Description: |
      CloudZero AWS AccountID; for cross-account Role Access
  IsResourceOwnerAccount:
    Type: String
    Description: |
      Should this template instantiate any resources?

Conditions: 
  CreateResources: !Equals [ !Ref IsResourceOwnerAccount, 'true' ]

Resources:
  Role: 
    Type: AWS::IAM::Role
    Condition: CreateResources
    Properties:
      Path: '/cloudzero/'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement: 
          - Effect: Allow
            Principal: 
              AWS: !Sub 'arn:aws:iam::${ReactorAccountId}:root'
            Action: 
              - 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalId
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
        - arn:aws:iam::aws:policy/AmazonSNSReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchEventsReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSXrayFullAccess
        - arn:aws:iam::aws:policy/AmazonGuardDutyReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonInspectorReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonRoute53ReadOnlyAccess

  RolePolicy:
    Type: AWS::IAM::Policy
    Condition: CreateResources
    Properties:
      PolicyName: !Sub 'cloudzero-resource-owner-policy-${ReactorAccountId}'
      PolicyDocument: 
        Version: 2012-10-17
        Statement: 
        - Sid: AccessCZLogGroups1
          Effect: Allow
          Action: logs:*
          Resource:
            - arn:aws:logs:*:*:log-group:/cz*:*:*
            - arn:aws:logs:*:*:log-group:/cz*
        - Sid: PassReactorRole1
          Effect: Allow
          Action:
            - iam:PassRole
          Resource: !GetAtt Role.Arn
        - Sid: ReducedViewOnly1
          Effect: Allow
          Action:
            - account:List*
            - a4b:List*
            - a4b:ResolveRoom
            - amplify:Get*
            - amplify:List*
            - appmesh:Describe*
            - appmesh:List*
            - application-autoscaling:Describe*
            - discovery:Describe*
            - discovery:List*
            - appstream:Describe*
            - appstream:List*
            - appsync:Get*
            - appsync:List*
            - artifact:Get*
            - athena:List*
            - autoscaling-plans:Describe*
            - autoscaling-plans:Get*
            - batch:Describe*
            - batch:List*
            - batch:ListJobs
            - aws-portal:View*
            - budgets:*
            - acm:Describe*
            - acm:List*
            - acm-pca:Describe*
            - acm-pca:List*
            - chatbot:Describe*
            - chime:Get*
            - chime:List*
            - clouddirectory:List*
            - clouddirectory:LookupPolicy
            - servicediscovery:DiscoverInstances
            - servicediscovery:Get*
            - servicediscovery:List*
            - cloud9:Describe*
            - cloud9:List*
            - cloudformation:Describe*
            - cloudformation:DetectStackDrift
            - cloudformation:DetectStackResourceDrift
            - cloudformation:Get*
            - cloudformation:List*
            - cloudfront:Get*
            - cloudfront:List*
            - cloudhsm:Describe*
            - cloudhsm:List*
            - cloudsearch:Describe*
            - cloudsearch:List*
            - cloudtrail:Get*
            - cloudtrail:List*
            - cloudtrail:LookupEvents
            - cloudtrail:Describe*
            - cloudwatch:Get*
            - cloudwatch:List*
            - cloudwatch:GetMetricData
            - applicationinsights:Describe*
            - applicationinsights:List*
            - logs:Describe*
            - logs:List*
            - logs:CreateLogStream
            - logs:CreateLogGroup
            - logs:PutSubscriptionFilter
            - logs:PutRetentionPolicy
            - signer:Describe*
            - signer:Get*
            - signer:List*
            - codebuild:List*
            - codebuild:ListBuilds*
            - codecommit:DescribePullRequestEvents
            - codecommit:GetBranch
            - codecommit:GetCommit*
            - codecommit:GetPullRequest
            - codecommit:GetRepository
            - codecommit:List*
            - codedeploy:Get*
            - codedeploy:List*
            - codepipeline:Get*
            - codepipeline:List*
            - codestar:Describe*
            - codestar:List*
            - codestar:Verify*
            - cognito-identity:Describe*
            - cognito-identity:GetIdentityPoolRoles
            - cognito-identity:List*
            - cognito-identity:LookupDeveloperIdentity
            - cognito-identity:ListIdentities
            - cognito-sync:Describe*
            - cognito-sync:Get*
            - cognito-sync:List*
            - cognito-sync:ListDatasets
            - cognito-idp:List*
            - comprehend:Describe*
            - comprehend:List*
            - config:DeliverConfigSnapshot
            - config:Describe*
            - config:Get*
            - config:List*
            - config:SelectResourceConfig
            - connect:Describe*
            - connect:GetCurrentMetricData
            - connect:GetMetricData
            - connect:List*
            - cur:*
            - ce:*
            - dlm:Get*
            - datapipeline:Describe*
            - datapipeline:Get*
            - datapipeline:List*
            - datapipeline:QueryObjects
            - datapipeline:GetAccountLimits
            - dms:Describe*
            - dms:List*
            - datasync:Describe*
            - datasync:List*
            - deeplens:Get*
            - deeplens:List*
            - devicefarm:Get*
            - devicefarm:List*
            - directconnect:Describe*
            - ds:Describe*
            - ds:Get*
            - ds:List*
            - dynamodb:Describe*
            - dynamodb:List*
            - dax:Describe*
            - dax:List*
            - ec2:Describe*
            - ec2:GetEbsDefaultKmsKeyId
            - ec2:GetEbsEncryptionByDefault
            - ec2:GetReservedInstancesExchangeQuote
            - ec2:GetTransitGatewayAttachmentPropagations
            - ec2:GetTransitGatewayRouteTableAssociations
            - ec2:GetTransitGatewayRouteTablePropagations
            - ec2:Get*
            - ec2:CreateFlowLogs
            - ec2:DescribeFlowLogs
            - autoscaling:Describe*
            - elasticbeanstalk:Describe*
            - elasticbeanstalk:List*
            - ecr:Describe*
            - ecr:GetLifecyclePolicy*
            - ecr:GetRepositoryPolicy
            - ecr:List*
            - ecs:Describe*
            - ecs:List*
            - eks:Describe*
            - eks:List*
            - elasticfilesystem:Describe*
            - elasticloadbalancing:Describe*
            - elasticmapreduce:Describe*
            - elasticmapreduce:List*
            - elastictranscoder:List*
            - elasticache:Describe*
            - elasticache:List*
            - es:Describe*
            - es:Get*
            - es:List*
            - aesop:Get*
            - aesop:List*
            - mediaconnect:Describe*
            - mediaconnect:List*
            - mediaconvert:Describe*
            - mediaconvert:Get*
            - mediaconvert:List*
            - medialive:Describe*
            - medialive:List*
            - mediapackage:Describe*
            - mediapackage:List*
            - mediapackage-vod:Describe*
            - mediapackage-vod:List*
            - mediastore:Describe*
            - mediastore:Get*
            - mediastore:List*
            - mediatailor:Get*
            - mediatailor:List*
            - events:Describe*
            - events:List*
            - events:ListRuleNamesByTarget
            - events:ListTargetsByRule
            - fms:Get*
            - fms:List*
            - freertos:Describe*
            - freertos:List*
            - fsx:Describe*
            - fsx:List*
            - gamelift:Describe*
            - gamelift:GetGameSessionLogUrl
            - gamelift:List*
            - glacier:Describe*
            - glacier:GetDataRetrievalPolicy
            - glacier:GetVaultAccessPolicy
            - glacier:GetVaultLock
            - glacier:GetVaultNotifications
            - glacier:List*
            - globalaccelerator:Describe*
            - globalaccelerator:List*
            - glue:List*
            - glue:Get*
            - groundstation:Get*
            - groundstation:List*
            - groundtruthlabeling:Describe*
            - groundtruthlabeling:List*
            - guardduty:Get*
            - guardduty:List*
            - health:Describe*
            - health:*
            - iam:Get*
            - iam:List*
            - iam:Simulate*
            - importexport:GetStatus
            - importexport:ListJobs
            - importexport:List*
            - inspector:Describe*
            - inspector:Get*
            - inspector:List*
            - iot:Describe*
            - iot:Get*
            - iot:List*
            - iot1click:Describe*
            - iot1click:Get*
            - iot1click:List*
            - iotanalytics:Describe*
            - iotanalytics:List*
            - iotevents:Describe*
            - iotevents:List*
            - greengrass:Get*
            - greengrass:List*
            - iotsitewise:Describe*
            - iotsitewise:List*
            - iotthingsgraph:Get*
            - iotthingsgraph:List*
            - kms:Describe*
            - kms:GetKeyPolicy
            - kms:GetKeyRotationStatus
            - kms:List*
            - kinesis:Describe*
            - kinesis:List*
            - kinesisanalytics:Describe*
            - kinesisanalytics:List*
            - firehose:Describe*
            - firehose:List*
            - kinesisvideo:Describe*
            - kinesisvideo:List*
            - lakeformation:Describe*
            - lakeformation:GetDataLakeSettings
            - lakeformation:List*
            - lambda:Get*
            - lambda:List*
            - lambda:GetAccountSettings
            - lambda:GetAlias
            - lambda:GetEventSourceMapping
            - lambda:GetFunctionConfiguration
            - lambda:GetPolicy
            - lex:Get*
            - license-manager:Get*
            - license-manager:List*
            - lightsail:Get*
            - machinelearning:Describe*
            - machinelearning:Get*
            - macie:List*
            - apigateway:GET
            - apigateway:OPTIONS
            - apigateway:HEAD
            - managedblockchain:Get*
            - managedblockchain:List*
            - kafka:Describe*
            - kafka:List*
            - mgh:Describe*
            - mgh:List*
            - mobileanalytics:Get*
            - mq:Describe*
            - mq:List*
            - opsworks:Describe*
            - opsworks:List*
            - opsworks-cm:Describe*
            - organizations:Describe*
            - organizations:List*
            - pi:Describe*
            - pi:Get*
            - personalize:Describe*
            - personalize:Get*
            - personalize:List*
            - mobiletargeting:Get*
            - mobiletargeting:List*
            - sms-voice:Get*
            - sms-voice:List*
            - polly:Get*
            - polly:List*
            - pricing:*
            - aws-marketplace:Describe*
            - aws-marketplace:List*
            - qldb:Describe*
            - qldb:List*
            - quicksight:List*
            - rds:Describe*
            - rds:List*
            - redshift:Describe*
            - redshift:List*
            - redshift:View*
            - rekognition:Describe*
            - rekognition:List*
            - ram:Get*
            - ram:List*
            - tag:Get*
            - resource-groups:Get*
            - resource-groups:List*
            - robomaker:Describe*
            - robomaker:List*
            - route53:Get*
            - route53:List*
            - route53resolver:Get*
            - route53resolver:List*
            - route53domains:Get*
            - route53domains:List*
            - route53domains:ViewBilling
            - s3:List*
            - s3:Get*
            - sagemaker:Describe*
            - sagemaker:List*
            - securityhub:Describe*
            - securityhub:Get*
            - securityhub:List*
            - sms:Get*
            - sms:List
            - serverlessrepo:Get*
            - serverlessrepo:List*
            - servicecatalog:Describe*
            - servicecatalog:List*
            - servicecatalog:ScanProvisionedProducts
            - servicecatalog:SearchProvisionedProducts
            - servicequotas:Get*
            - servicequotas:List*
            - ses:Get*
            - ses:List*
            - shield:Describe*
            - shield:Get*
            - shield:List*
            - swf:Describe*
            - swf:Get*
            - swf:List*
            - sdb:DomainMetadata
            - sdb:ListDomains
            - sdb:List*
            - snowball:Describe*
            - snowball:List*
            - sns:List*
            - sns:Get*
            - sqs:List*
            - sqs:Get*
            - sso:Describe*
            - sso:Get*
            - sso:List*
            - sso-directory:Describe*
            - sso-directory:List*
            - states:Describe*
            - states:Get*
            - states:List*
            - states:ListActivities
            - states:ListStateMachines
            - storagegateway:Describe*
            - storagegateway:List*
            - ssm:Describe*
            - ssm:Get*
            - ssm:List*
            - ssm:ListAssociations
            - ssm:ListDocuments
            - transcribe:Get*
            - transcribe:List*
            - transfer:Describe*
            - transfer:List*
            - translate:Get*
            - translate:List*
            - trustedadvisor:Describe*
            - waf:Get*
            - waf:List*
            - waf-regional:Get*
            - waf-regional:List*
            - wellarchitected:Get*
            - wellarchitected:List*
            - workdocs:Describe*
            - workdocs:Get*
            - worklink:Describe*
            - worklink:List*
            - workmail:Describe*
            - workmail:Get*
            - workmail:List*
            - workspaces:Describe*
            - workspaces:List*
            - xray:Get*
            - xray:Batch*
          Resource: "*"
        - Sid: CZProtect20190905
          Effect: Deny
          Action:
            - aws-portal:*PaymentMethods
            - aws-portal:*Account
            - glue:GetConnection
            - iam:GetServerCertificate
            - iam:GetSSHPublicKey
            - lambda:GetFunction
            - s3:GetObject*
          Resource: "*"
      Roles: 
        - !Ref Role

Outputs:
  RoleArn:
    Condition: CreateResources
    Value: !GetAtt Role.Arn
    Description: Resource Owner Cross Account Role ARN
