# -*- coding: utf-8 -*-
# Copyright (c) 2016-present, CloudZero, Inc. All rights reserved.
# Licensed under the BSD-style license. See LICENSE file in the project root for full license information.

AWSTemplateFormatVersion: '2010-09-09'
Description: CloudZero Resource Owner Account Template

Parameters:
  ExternalId:
    Type: String
    Description: |
      Unique ExternalId for Customer Organization; for cross-account Role Access and
      associating this template with a Customer Organization
  ReactorAccountId:
    Type: String
    Description: |
      CloudZero AWS AccountID; for cross-account Role Access
  IsResourceOwnerAccount:
    Type: String
    Description: |
      Should this template instantiate any resources?

Conditions:
  CreateResources: !Equals [ !Ref IsResourceOwnerAccount, 'true' ]

Resources:
  Role:
    Type: AWS::IAM::Role
    Condition: CreateResources
    Properties:
      Path: '/cloudzero/'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${ReactorAccountId}:root'
            Action:
              - 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalId
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
        - arn:aws:iam::aws:policy/SecurityAudit
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
        - arn:aws:iam::aws:policy/job-function/Billing
        - arn:aws:iam::aws:policy/AWSBillingReadOnlyAccess

  RolePolicy:
    Type: AWS::IAM::Policy
    Condition: CreateResources
    Properties:
      PolicyName: !Sub 'cloudzero-resource-owner-policy-${ReactorAccountId}'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: CZCostMonitoring20240422
            Effect: Allow
            Action:
              - account:GetAccountInformation
              - billing:Get*
              - budgets:Describe*
              - budgets:View*
              - ce:Describe*
              - ce:Get*
              - ce:List*
              - consolidatedbilling:Get*
              - consolidatedbilling:List*
              - cur:Describe*
              - cur:Get*
              - cur:Validate*
              - cur:List*
              - freetier:Get*
              - invoicing:Get*
              - invoicing:List*
              - organizations:Describe*
              - organizations:List*
              - payments:Get*
              - payments:List*
              - pricing:*
              - tax:Get*
              - tax:List*
            Resource: "*"
          - Sid: CZActivityMonitoring20210423
            Effect: Allow
            Action:
              - cloudtrail:Get*
              - cloudtrail:List*
              - cloudtrail:Describe*
              - health:Describe*
              - support:DescribeTrustedAdvisor*
              - servicequotas:Get*
              - servicequotas:List*
              - resource-groups:Get*
              - resource-groups:List*
              - resource-groups:Search*
              - cloudformation:DescribeStacks
              - cloudformation:ListStackResources
              - tag:Get*
              - tag:Describe*
              - resource-explorer:List*
              - account:ListRegions
            Resource: "*"
          - Sid: CZReservedCapacity20190912
            Effect: Allow
            Action:
              - dynamodb:DescribeReserved*
              - ec2:DescribeReserved*
              - elasticache:DescribeReserved*
              - es:DescribeReserved*
              - rds:DescribeReserved*
              - redshift:DescribeReserved*
            Resource: "*"
          - Sid: CloudZeroContainerInsightsAccess20210423
            Effect: Allow
            Action:
              - logs:List*
              - logs:Describe*
              - logs:StartQuery
              - logs:StopQuery
              - logs:Filter*
              - logs:Get*
            Resource: arn:aws:logs:*:*:log-group:/aws/containerinsights/*
          - Sid: CloudZeroCloudWatchContainerLogStreamAccess20210906
            Effect: Allow
            Action:
              - logs:GetQueryResults
              - logs:DescribeLogGroups
            Resource: arn:aws:logs:*:*:log-group::log-stream:*
          - Sid: CloudZeroCloudWatchMetricsAccess20210423
            Effect: Allow
            Action:
              - autoscaling:Describe*
              - cloudwatch:Describe*
              - cloudwatch:Get*
              - cloudwatch:List*
            Resource: "*"
      Roles:
        - !Ref Role

Outputs:
  RoleArn:
    Condition: CreateResources
    Value: !GetAtt Role.Arn
    Description: Resource Owner Cross Account Role ARN
