# -*- coding: utf-8 -*-
# Copyright (c) 2016-present, CloudZero, Inc. All rights reserved.
# Licensed under the BSD-style license. See LICENSE file in the project root for full license information.

AWSTemplateFormatVersion: '2010-09-09'
Description: CloudZero Resource Owner Account Template

Parameters:
  ExternalId:
    Type: String
    Description: |
      Unique ExternalId for Customer Organization; for cross-account Role Access and
      associating this template with a Customer Organization
  ReactorAccountId:
    Type: String
    Description: |
      CloudZero AWS AccountID; for cross-account Role Access
  IsResourceOwnerAccount:
    Type: String
    Description: |
      Should this template instantiate any resources?

Conditions: 
  CreateResources: !Equals [ !Ref IsResourceOwnerAccount, 'true' ]

Resources:
  Role: 
    Type: AWS::IAM::Role
    Condition: CreateResources
    Properties:
      Path: '/cloudzero/'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement: 
          - Effect: Allow
            Principal: 
              AWS: !Sub 'arn:aws:iam::${ReactorAccountId}:root'
            Action: 
              - 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalId
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSXrayReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
        - arn:aws:iam::aws:policy/SecurityAudit
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
        - arn:aws:iam::aws:policy/job-function/Billing

  RolePolicy:
    Type: AWS::IAM::Policy
    Condition: CreateResources
    Properties:
      PolicyName: !Sub 'cloudzero-resource-owner-policy-${ReactorAccountId}'
      PolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Sid: CZProtect20190912
            Effect: Deny
            Action:
              - aws-portal:*PaymentMethods
              - aws-portal:*Account
              - ec2:GetPasswordData
              - ec2:GetConsoleOutput
              - ec2:GetConsoleScreenshot
              - glue:GetConnection
            Resource: '*'
          - Sid: CZCostMonitoring20191111
            Effect: Allow
            Action:
              - aws-portal:View*
              - ce:*
              - cur:Describe*
              - budgets:*
              - pricing:*
              - organizations:Describe*
              - organizations:List*
            Resource: '*'
          - Sid: CZActivityMonitoring20210411
            Effect: Allow
            Action:
              - cloudtrail:Get*
              - cloudtrail:List*
              - cloudtrail:Describe*
              - health:*
              - support:DescribeTrustedAdvisor*
              - servicequotas:Get*
              - servicequotas:List*
              - resource-groups:Get*
              - resource-groups:List*
              - resource-groups:Search*
              - cloudformation:Describe*
              - cloudformation:List*
              - tag:Get*
              - tag:Describe*
              - resource-explorer:List*
              - account:ListRegions
            Resource: '*'
          - Sid: CZReservedCapacity20190912
            Effect: Allow
            Action:
              - cloudfront:Get*
              - cloudfront:List*
              - dynamodb:Describe*
              - dynamodb:List*
              - ec2:Describe*
              - ec2:Get*
              - ec2:Get*
              - elasticache:Describe*
              - elasticache:List*
              - elasticmapreduce:Describe*
              - elasticmapreduce:List*
              - es:Describe*
              - es:List*
              - es:Get*
              - rds:Describe*
              - redshift:Describe*
              - redshift:List*
            Resource: '*'
      Roles: 
        - !Ref Role

Outputs:
  RoleArn:
    Condition: CreateResources
    Value: !GetAtt Role.Arn
    Description: Resource Owner Cross Account Role ARN
