# Copyright (c) 2024 CloudZero - ALL RIGHTS RESERVED - PROPRIETARY AND CONFIDENTIAL
# Unauthorized copying of this file and/or project, via any medium is strictly prohibited.
# Direct all questions to legal@cloudzero.com

name: CD Dev

on:
  workflow_dispatch:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write
  contents: read

jobs:
  cd-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.SAM_DEPLOY_ROLE_ARN }}
          aws-region: us-east-1
      - name: Upload S3 Artifacts
        shell: bash
        run: make deploy version='dev' regions='us-east-1 us-east-2 us-west-1'
      
  merg-to-master:
    runs-on: ubuntu-latest
    needs: cd-dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Merge from develop to master
        uses: ./.github/actions/merge-from-to
        with:
          from-branch: develop
          from-sha: ${{ github.sha }}
          to: master
        