# Copyright (c) 2024 CloudZero - ALL RIGHTS RESERVED - PROPRIETARY AND CONFIDENTIAL
# Unauthorized copying of this file and/or project, via any medium is strictly prohibited.
# Direct all questions to legal@cloudzero.com

name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main'  && github.ref != 'refs/heads/develop'}}

env:
  AWS_DEFAULT_REGION: us-east-1

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Init
        uses: ./.github/actions/init
        with:
          python-version: 3.11.9
      - name: Lint
        shell: bash
        run: make lint
      - name: Test
        shell: bash
        run: make test
